# Generated by Django 2.0.2 on 2018-03-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('provider_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('provider_id', models.CharField(max_length=250)),
                ('display_name', models.CharField(max_length=250)),
                ('logo_url', models.TextField()),
                ('scopes', models.TextField()),
            ],
        ),
    ]
