# Generated by Django 2.0.2 on 2018-03-03 17:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 3, 17, 1, 45, 621364, tzinfo=utc)),
        ),
    ]
