# Generated by Django 2.0.2 on 2018-03-04 22:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tl', '0004_auto_20180303_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providers',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 22, 22, 15, 676414, tzinfo=utc)),
        ),
    ]
