# Generated by Django 2.0.2 on 2018-03-05 17:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tl', '0005_auto_20180304_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='tl_info',
            fields=[
                ('client_id', models.TextField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=250)),
                ('client_secret', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='providers',
            name='provider_uuid',
        ),
        migrations.AlterField(
            model_name='providers',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 17, 42, 6, 754440, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='providers',
            name='provider_id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
