# Generated by Django 2.0.2 on 2018-03-05 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tl', '0006_auto_20180305_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providers',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 17, 50, 30, 638269, tzinfo=utc)),
        ),
    ]
