# Generated by Django 2.0.2 on 2018-03-05 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl', '0007_auto_20180305_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providers',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 17, 52, 3, 362311)),
        ),
    ]
