# Generated by Django 2.0.2 on 2018-03-05 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl', '0009_auto_20180305_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providers',
            options={'verbose_name': 'TrueLayer Provider', 'verbose_name_plural': 'TrueLayer Providers'},
        ),
        migrations.AlterModelOptions(
            name='tl_info',
            options={'verbose_name': 'TrueLayer Keys', 'verbose_name_plural': 'TrueLayer Keys'},
        ),
        migrations.AddField(
            model_name='tl_info',
            name='redirect_uri',
            field=models.TextField(default='test'),
        ),
        migrations.AlterField(
            model_name='providers',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 23, 17, 11, 688156)),
        ),
    ]
