# Generated by Django 2.0.2 on 2018-03-05 23:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tl', '0010_auto_20180305_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_token', models.TextField()),
                ('r_token', models.TextField()),
                ('token_type', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='tl_info',
            name='token_url',
            field=models.TextField(default='text'),
        ),
        migrations.AlterField(
            model_name='providers',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 23, 21, 7, 8195)),
        ),
        migrations.AlterField(
            model_name='tl_info',
            name='redirect_uri',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='token',
            name='provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tl.Providers'),
        ),
        migrations.AddField(
            model_name='token',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
