# Generated by Django 2.0.2 on 2018-03-05 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl', '0011_auto_20180305_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='a_token',
            new_name='access_token',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='r_token',
            new_name='refresh_token',
        ),
        migrations.AlterField(
            model_name='providers',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 23, 38, 23, 705660)),
        ),
    ]
