# Generated by Django 2.0.2 on 2018-03-06 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl', '0013_auto_20180305_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providers',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 0, 1, 2, 467338)),
        ),
    ]
