# Generated by Django 2.0.2 on 2018-03-06 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl', '0017_auto_20180306_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providers',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 8, 55, 30, 636039)),
        ),
    ]
