# Generated by Django 2.0.2 on 2018-03-06 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl', '0021_auto_20180306_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providers',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 11, 17, 656494)),
        ),
    ]
