# Generated by Django 2.0.2 on 2018-03-06 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl', '0022_auto_20180306_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='providers',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 6, 10, 12, 26, 281965)),
        ),
    ]
